### ISSUE TITLE
Title & Abstract

### ISSUE THREAD

**Issue by ghost** [merliseclyde/sta701-F23#15]
Fill in the YAML below and add your abstract below
---
title: "Bayesian fault localization for software testing"

author: "Irene Ji"

date: "Sep 18, 2023"

---

## Abstract 

Fault localization is a software testing activity that is critical when software failures occur. We propose a novel Bayesian fault localization method, yielding a principled and probabilistic ranking of suspicious input combinations for identifying the root causes of failures. We are currently developing methods to use the calculated probabilities for sequential test case generation.

### Advisor(s)

Simon Mak

**Comment by merliseclyde** [comment]
Thanks!   Should appear on the website shortly!
