### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by OlivierBinette** [merliseclyde/sta701-F23#5]
## Name: 

Olivier Binette

## Title:

Performance Rank Reversals: An Overlooked Challenge in the Evaluation of Machine Learning Algorithms

## Abstract

I'll talk about research done at Los Alamos National Laboratory over the summer.

## Advisor(s)

Jerry Reiter

**Comment by merliseclyde** [comment]
Olivier,

please add more detail to your abstract that supports what you did and found.

**Comment by OlivierBinette** [comment]
@merliseclyde Cancelled talk, see #8
