### ISSUE TITLE
Cancelling talk

### ISSUE THREAD

**Issue by OlivierBinette** [merliseclyde/sta701-F23#8]
## Name: 

Olivier Binette

## Current Date for Talk: 

2023-09-18

## Alternate Day(s) for Talk: 

Late pring 2024, unless I graduate before.

## Are either of the speakers for the Alternate Day willing to switch slots? 

None

**Comment by merliseclyde** [comment]
Looking forward to the talk - if you wish to update the title or abstract, please create a new Title/Abstract Issue
